### ISSUE TITLE
Still to do

### ISSUE THREAD

**Issue by pjgaudre** [pjgaudre/Birds#1]
1. Add labels for every sound file. We need to figure out a way to store the folder name, which will act as the label for every sound file that passes through our feature extraction algorithm.
2. Add the features you guys think would be useful.

**Comment by ntahmase** [comment]
since we want to identify,

we can set

K = number of species;
y = zeros(1, K);


Then if the species #3 exists in the file, then the third element of y is
1.

Am I right?




On Mon, Nov 16, 2015 at 6:14 PM, Philippe Gaudreau <notifications@github.com
> wrote:

>
>    1.
>
>    Add labels for every sound file. We need to figure out a way to store
>    the folder name, which will act as the label for every sound file that
>    passes through our feature extraction algorithm.
>    2.
>
>    Add the features you guys think would be useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pjgaudre/Birds/issues/1>.
>



-- 
* Nazanin Tahmasebi*

**Comment by ntahmase** [comment]
Hi Philippe,

Do you use for loop to read the waves in each folder? If yes, how do you
use it?

On Mon, Nov 16, 2015 at 6:21 PM, Nazanin Tahmasebi <ntahmase@ualberta.ca>
wrote:

> since we want to identify,
>
> we can set
>
> K = number of species;
> y = zeros(1, K);
>
>
> Then if the species #3 exists in the file, then the third element of y is
> 1.
>
> Am I right?
>
>
>
>
> On Mon, Nov 16, 2015 at 6:14 PM, Philippe Gaudreau <
> notifications@github.com> wrote:
>
>>
>>    1.
>>
>>    Add labels for every sound file. We need to figure out a way to store
>>    the folder name, which will act as the label for every sound file that
>>    passes through our feature extraction algorithm.
>>    2.
>>
>>    Add the features you guys think would be useful.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pjgaudre/Birds/issues/1>.
>>
>
>
>
> --
> * Nazanin Tahmasebi*
>
>


-- 
* Nazanin Tahmasebi*

**Comment by pjgaudre** [comment]
I was planning on doing something similar to this:
http://stackoverflow.com/questions/14958516/looping-through-all-files-in-directory-in-r-applying-multiple-commands

files <- list.files(path="path/to/dir", pattern="*.txt", full.names=T, recursive=FALSE)
lapply(files, function(x) {
    t <- read.table(x, header=T) # load file
    # apply function
    out <- function(t)
    # write to file
    write.table(out, "path/to/output", sep="\t", quote=F, row.names=F, col.names=T)
})

**Comment by pjgaudre** [comment]
Here is another website that will prove useful!

https://psychwire.wordpress.com/2011/06/03/merge-all-files-in-a-directory-using-r-into-a-single-dataframe/

**Comment by carlosshigoto** [comment]
I'm so sorry, for not dedicating time to this project late.

Recall this lines Phil,

    files <- list.files(recursive = T)
    for (f in file){
         Function(f)
    }

While in the top directory.

Carlos Contreras

E-mail: carloscontrerasc@gmail.com

**Comment by pjgaudre** [comment]
Thanks Carlos,

To combine all the information into one dataframe, I will the code will looks something like this:

setwd("target_dir/")
files <- list.files(recursive = T)
for (f in file){
        table<-Function(f)

  # if the merged dataset doesn't exist, create it
  if (!exists("dataset")){
    dataset <- read.table(file, header=TRUE, sep="\t")
  }
   
  # if the merged dataset does exist, append to it
  if (exists("dataset")){
    temp_dataset <-read.table(file, header=TRUE, sep="\t")
    dataset<-rbind(dataset, temp_dataset)
    rm(temp_dataset)

    }

**Comment by carlosshigoto** [comment]
That looks good.

Carlos Contreras

E-mail: carloscontrerasc@gmail.com

**Comment by pjgaudre** [comment]
For the label, I just figured it out!

we can use the function dirname 

https://stat.ethz.ch/R-manual/R-devel/library/base/html/basename.html

**Comment by pjgaudre** [comment]
Alright Nazanin, I just wrote the function for feature extraction. All you need to do now is add your own features to the function features.

**Comment by ntahmase** [comment]
Thanks


On Mon, Nov 16, 2015 at 9:19 PM, Philippe Gaudreau <notifications@github.com
> wrote:

> Alright Nazanin, I just wrote the function for feature extraction. All you
> need to do now is add your own features to the function features.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pjgaudre/Birds/issues/1#issuecomment-157263849>.
>



-- 
* Nazanin Tahmasebi*

**Comment by pjgaudre** [comment]
For those of you looking for inspiration

An Introduction to the soundecology Package:
https://cran.r-project.org/web/packages/soundecology/vignettes/intro.html
https://cran.r-project.org/web/packages/soundecology/soundecology.pdf

Lots of features in there!!!! :)

**Comment by ntahmase** [comment]
I just added

ndsi: Normalized Difference Soundscape Index

On Mon, Nov 16, 2015 at 9:24 PM, Philippe Gaudreau <notifications@github.com
> wrote:

> For those of you looking for inspiration
>
> An Introduction to the soundecology Package:
> https://cran.r-project.org/web/packages/soundecology/vignettes/intro.html
> https://cran.r-project.org/web/packages/soundecology/soundecology.pdf
>
> Lots of features in there!!!! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pjgaudre/Birds/issues/1#issuecomment-157264426>.
>



-- 
* Nazanin Tahmasebi*
